WIN_FACTOR = 1.5
LOSS_FACTOR = 1.08
DRIVES_PER_TEAM = 12
BASE_PASS_FREQ = 0.5
OT_START_YARD_LINE = 75
BASE_COMP_PERCENT = 0.62
BASE_SACK_RATE = 0.07
BASE_INT_RATE = 0.07
BASE_FUMBLE_RATE = 0.02
FIELD_GOAL_RANGE = 60

# Ranking constants
POLL_INERTIA_WIN_BONUS = 172
POLL_INERTIA_LOSS_PENALTY = 157
RANKING_TOTAL_WEEKS = 12

# Test constants
TEST_SIMULATIONS = 200
TEST_SIM_RATING_DIFF = 10

# Yards simulation constants
PASS_BASE_MEAN = 7
PASS_STD_DEV = 5.2
PASS_ADVANTAGE_FACTOR = 0.1
PASS_POSITIVE_MULTIPLIER = 0.004
PASS_POSITIVE_POWER = 3.2

SACK_BASE_MEAN = -6
SACK_STD_DEV = 2

RUN_BASE_MEAN = 2.8  
RUN_STD_DEV = 5.5  
RUN_ADVANTAGE_FACTOR = 0
RUN_POSITIVE_MULTIPLIER = 0.0004  
RUN_POSITIVE_POWER = 4.2  
