REGULAR_SEASON_WEEKS = 14
REGULAR_SEASON_GAMES = 12
CONFERENCE_CHAMPIONSHIP_WEEK = REGULAR_SEASON_WEEKS + 1
LAST_WEEK_BY_PLAYOFF_TEAMS = {
    2: CONFERENCE_CHAMPIONSHIP_WEEK + 1,
    4: CONFERENCE_CHAMPIONSHIP_WEEK + 2,
    12: CONFERENCE_CHAMPIONSHIP_WEEK + 4,
}
