# Generated by Django 4.2.3 on 2023-07-25 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confName', models.CharField(max_length=255)),
                ('confFullName', models.CharField(max_length=255)),
                ('confGames', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Drives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameID', models.IntegerField()),
                ('driveID', models.IntegerField()),
                ('offense', models.CharField(max_length=255)),
                ('defense', models.CharField(max_length=255)),
                ('startingFP', models.IntegerField()),
                ('result', models.CharField(max_length=255)),
                ('yards', models.IntegerField()),
                ('playCount', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameID', models.IntegerField()),
                ('team', models.CharField(max_length=255)),
                ('opponent', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255, null=True)),
                ('spread', models.CharField(max_length=10)),
                ('moneyline', models.CharField(max_length=10)),
                ('winProb', models.FloatField()),
                ('weekPlayed', models.IntegerField()),
                ('gameNum', models.IntegerField()),
                ('result', models.CharField(max_length=10)),
                ('overtime', models.IntegerField()),
                ('score', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameID', models.IntegerField()),
                ('driveID', models.IntegerField()),
                ('offense', models.CharField(max_length=50)),
                ('defense', models.CharField(max_length=50)),
                ('startingFP', models.IntegerField()),
                ('down', models.IntegerField()),
                ('yardsLeft', models.IntegerField()),
                ('playType', models.CharField(max_length=50)),
                ('yardsGained', models.IntegerField()),
                ('result', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(max_length=10)),
                ('prestige', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('mascot', models.CharField(max_length=255)),
                ('colorPrimary', models.CharField(max_length=7)),
                ('colorSecondary', models.CharField(max_length=7)),
                ('conference', models.CharField(max_length=255, null=True)),
                ('confWins', models.IntegerField()),
                ('confLosses', models.IntegerField()),
                ('nonConfWins', models.IntegerField()),
                ('nonConfLosses', models.IntegerField()),
                ('totalWins', models.IntegerField()),
                ('totalLosses', models.IntegerField()),
                ('resume', models.FloatField()),
                ('expectedWins', models.FloatField()),
                ('ranking', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=20)),
                ('last', models.CharField(max_length=20)),
                ('pos', models.CharField(max_length=2)),
                ('starter', models.BooleanField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.teams')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentWeek', models.IntegerField()),
                ('currentYear', models.IntegerField()),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='start.teams')),
            ],
        ),
    ]
