# Generated by Django 4.1.4 on 2023-02-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confName', models.CharField(max_length=255)),
                ('confFullName', models.CharField(max_length=10)),
                ('confGames', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Drives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameID', models.IntegerField()),
                ('driveID', models.IntegerField()),
                ('offense', models.CharField(max_length=255)),
                ('defense', models.CharField(max_length=255)),
                ('startingFP', models.IntegerField()),
                ('result', models.CharField(max_length=255)),
                ('yards', models.IntegerField()),
                ('playCount', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameID', models.IntegerField()),
                ('team', models.CharField(max_length=255)),
                ('opponent', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255, null=True)),
                ('spread', models.CharField(max_length=10)),
                ('moneyline', models.CharField(max_length=10)),
                ('winProb', models.FloatField()),
                ('weekPlayed', models.IntegerField()),
                ('gameNum', models.IntegerField()),
                ('result', models.CharField(max_length=10)),
                ('score', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameID', models.IntegerField()),
                ('driveID', models.IntegerField()),
                ('offense', models.CharField(max_length=255)),
                ('defense', models.CharField(max_length=255)),
                ('startingFP', models.IntegerField()),
                ('down', models.IntegerField()),
                ('yardsLeft', models.IntegerField()),
                ('playType', models.CharField(max_length=255)),
                ('yardsGained', models.IntegerField()),
                ('result', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=10)),
                ('prestige', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('mascot', models.CharField(max_length=255)),
                ('colorPrimary', models.CharField(max_length=7)),
                ('colorSecondary', models.CharField(max_length=7)),
                ('conference', models.CharField(max_length=255, null=True)),
                ('confWins', models.IntegerField()),
                ('confLosses', models.IntegerField()),
                ('nonConfWins', models.IntegerField()),
                ('nonConfLosses', models.IntegerField()),
                ('totalWins', models.IntegerField()),
                ('totalLosses', models.IntegerField()),
                ('resume', models.FloatField()),
                ('expectedWins', models.FloatField()),
                ('ranking', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentWeek', models.IntegerField()),
            ],
        ),
    ]
