# Generated by Django 4.1.4 on 2023-04-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0002_alter_info_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='starter',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
