export const ROUTES = {
  HOME: '/',
  NONCON: '/noncon',
  DASHBOARD: '/dashboard',
  RANKINGS: '/rankings',
  TEAM_SCHEDULE: '/:teamName/schedule',
  TEAM_ROSTER: '/:teamName/roster',
  TEAM_HISTORY: '/:teamName/history',
  PLAYOFF: '/playoff',
  STANDINGS: '/standings/:conference_name',
  PLAYER: '/players/:playerId',
  WEEK_SCHEDULE: '/schedule/:week',
  GAME: '/game/:id',
  TEAM_STATS: '/stats/team',
  INDIVIDUAL_STATS: '/stats/individual',
  RATINGS_STATS: '/stats/ratings',
  SEASON_SUMMARY: '/summary',
  ROSTER_PROGRESSION: '/roster_progression',
  RECRUITING_SUMMARY: '/recruiting_summary',
  ROSTER_CUTS: '/roster_cuts',
  REALIGNMENT: '/realignment',
  SETTINGS: '/settings',
  AWARDS: '/awards',
} as const;
