export const ROUTES = {
  HOME: '/',
  NEW_LEAGUE: '/new',
  NONCON: '/noncon',
  DASHBOARD: '/dashboard',
  NEWS: '/news',
  LEAGUE_HISTORY: '/league/history',
  LEAGUE_HISTORY_YEAR: '/league/history/:year',
  LEAGUE_RECORDS: '/league/records',
  RANKINGS: '/rankings',
  TEAM_SCHEDULE: '/:teamName/schedule',
  TEAM_ROSTER: '/:teamName/roster',
  TEAM_STATS: '/:teamName/stats/:year?',
  TEAM_HISTORY: '/:teamName/history',
  PLAYOFF: '/playoff',
  PLAYOFF_PICTURE: '/playoff/picture',
  PLAYOFF_RESUMES: '/playoff/resumes',
  PLAYOFF_PROJECTIONS: '/playoff/projections',
  BOWL_GAMES: '/playoff/bowls',
  STANDINGS: '/standings/:conference_name',
  PLAYER: '/players/:playerId',
  WEEK_SCHEDULE: '/schedule/:week',
  GAME: '/game/:id',
  TEAM_RANKINGS: '/stats/teams/:year?',
  ADVANCED_STATS: '/stats/advanced',
  PLAYER_LEADERS: '/stats/players/:year?',
  RATINGS_STATS: '/stats/ratings',
  SEASON_SUMMARY: '/summary',
  ROSTER_PROGRESSION: '/roster_progression',
  RECRUITING: '/recruiting',
  RECRUITING_SUMMARY: '/recruiting_summary',
  ROSTER_CUTS: '/roster_cuts',
  REALIGNMENT: '/realignment',
  AWARDS: '/awards',
} as const;

export const getLeagueHistoryPath = (year: number) => `/league/history/${year}`;

export const getTeamStatsPath = (teamName: string, year?: number) =>
  `/${teamName}/stats${year === undefined ? '' : `/${year}`}`;
