import type { loadHomeData, loadNonCon, loadDashboard, loadTeamSchedule, loadWeekSchedule, loadGame, listAvailableTeams, startNewLeague } from '../domain/league/loaders/season';
import type { loadAwards, loadSeasonSummary, loadRealignment, loadRosterProgression, loadRecruitingSummary, loadRosterCuts } from '../domain/league/loaders/offseason';
import type { loadRankings, loadSettings } from '../domain/league/loaders';
import type { loadRatingsStats, loadStandings } from '../domain/league/loaders/stats';
import type { loadTeamRoster, loadTeamHistory, loadPlayer, getTeamInfo } from '../domain/league/loaders/team';
import type { loadPlayoff } from '../domain/league/loaders/playoff';
import type { loadIndividualStats } from '../domain/league/stats';

export type HomePageData = Awaited<ReturnType<typeof loadHomeData>>;
export type NonConPageData = Awaited<ReturnType<typeof loadNonCon>>;
export type DashboardPageData = Awaited<ReturnType<typeof loadDashboard>>;
export type TeamSchedulePageData = Awaited<ReturnType<typeof loadTeamSchedule>>;
export type WeekSchedulePageData = Awaited<ReturnType<typeof loadWeekSchedule>>;
export type GamePageData = Awaited<ReturnType<typeof loadGame>>;
export type AwardsPageData = Awaited<ReturnType<typeof loadAwards>>;
export type SeasonSummaryPageData = Awaited<ReturnType<typeof loadSeasonSummary>>;
export type RealignmentPageData = Awaited<ReturnType<typeof loadRealignment>>;
export type RosterProgressionPageData = Awaited<ReturnType<typeof loadRosterProgression>>;
export type RecruitingSummaryPageData = Awaited<ReturnType<typeof loadRecruitingSummary>>;
export type RosterCutsPageData = Awaited<ReturnType<typeof loadRosterCuts>>;
export type RatingsStatsPageData = Awaited<ReturnType<typeof loadRatingsStats>>;
export type StandingsPageData = Awaited<ReturnType<typeof loadStandings>>;
export type TeamRosterPageData = Awaited<ReturnType<typeof loadTeamRoster>>;
export type TeamHistoryPageData = Awaited<ReturnType<typeof loadTeamHistory>>;
export type RankingsPageData = Awaited<ReturnType<typeof loadRankings>>;
export type SettingsPageData = Awaited<ReturnType<typeof loadSettings>>;
export type PlayerPageData = Awaited<ReturnType<typeof loadPlayer>>;
export type TeamInfoData = Awaited<ReturnType<typeof getTeamInfo>>;
export type AvailableTeamsData = Awaited<ReturnType<typeof listAvailableTeams>>;
export type StartNewLeagueData = Awaited<ReturnType<typeof startNewLeague>>;
export type IndividualStatsPageData = Awaited<ReturnType<typeof loadIndividualStats>>;
export type PlayoffPageData = Awaited<ReturnType<typeof loadPlayoff>>;
