import type { listAvailableOpponents } from '../domain/league/loaders/season/listAvailableOpponents';
import type { loadDashboard } from '../domain/league/loaders/season/loadDashboard';
import type { loadLeagueHistory } from '../domain/league/loaders/leagueHistory';
import type { loadLeagueRecords } from '../domain/league/loaders/leagueRecords';
import type { loadBiggestUpsets } from '../domain/league/loaders/biggestUpsets';
import type { loadGame } from '../domain/league/loaders/season/loadGame';
import type { loadHomeData } from '../domain/league/loaders/season/loadHomeData';
import type { loadNews } from '../domain/league/loaders/season/loadNews';
import type { loadNonCon } from '../domain/league/loaders/season/loadNonCon';
import type { loadTeamSchedule } from '../domain/league/loaders/season/loadTeamSchedule';
import type { loadWeekSchedule } from '../domain/league/loaders/season/loadWeekSchedule';
import type { loadAwards } from '../domain/league/loaders/awards';
import type { loadSeasonSummary } from '../domain/league/loaders/seasonSummary';
import type { loadRosterCuts } from '../domain/league/loaders/loadRosterCuts';
import type { loadRealignment } from '../domain/league/loaders/loadRealignment';
import type { loadRecruitingSummary } from '../domain/league/loaders/loadRecruitingSummary';
import type { loadRecruiting } from '../domain/league/loaders/loadRecruiting';
import type { loadRosterProgression } from '../domain/league/loaders/loadRosterProgression';
import type { loadRankings } from '../domain/league/loaders/rankings';
import type { loadRatingsStats } from '../domain/league/loaders/ratingsStats';
import type { loadStandings } from '../domain/league/loaders/standings';
import type { loadPlayerLeaders } from '../domain/league/loaders/stats/playerLeaders';
import type { loadTeamRankings } from '../domain/league/loaders/stats/teamRankings';
import type { getTeamInfo } from '../domain/league/loaders/team/getTeamInfo';
import type { loadPlayer } from '../domain/league/loaders/team/loadPlayer';
import type { loadTeamHistory } from '../domain/league/loaders/team/loadTeamHistory';
import type { loadTeamRoster } from '../domain/league/loaders/team/loadTeamRoster';
import type { loadTeamStats } from '../domain/league/loaders/team/loadTeamStats';
import type { loadBowlGames } from '../domain/league/loaders/postseason/loadBowlGames';
import type { loadPlayoffBracket } from '../domain/league/loaders/postseason/loadPlayoffBracket';
import type { loadPlayoffPicture } from '../domain/league/loaders/postseason/loadPlayoffPicture';
import type { loadResumeComparison } from '../domain/league/loaders/postseason/loadResumeComparison';
import type {
  loadAdvancedStats,
  loadPostseasonProjections,
} from '../domain/league/loaders/roadmap';

export type HomePageData = Awaited<ReturnType<typeof loadHomeData>>;
export type NonConPageData = Awaited<ReturnType<typeof loadNonCon>>;
export type DashboardPageData = Awaited<ReturnType<typeof loadDashboard>>;
export type LeagueHistoryPageData = Awaited<ReturnType<typeof loadLeagueHistory>>;
export type LeagueRecordsPageData = Awaited<ReturnType<typeof loadLeagueRecords>>;
export type BiggestUpsetsPageData = Awaited<ReturnType<typeof loadBiggestUpsets>>;
export type NewsPageData = Awaited<ReturnType<typeof loadNews>>;
export type TeamSchedulePageData = Awaited<ReturnType<typeof loadTeamSchedule>>;
export type WeekSchedulePageData = Awaited<ReturnType<typeof loadWeekSchedule>>;
export type GamePageData = Awaited<ReturnType<typeof loadGame>>;
export type AwardsPageData = Awaited<ReturnType<typeof loadAwards>>;
export type SeasonSummaryPageData = Awaited<ReturnType<typeof loadSeasonSummary>>;
export type RealignmentPageData = Awaited<ReturnType<typeof loadRealignment>>;
export type RosterProgressionPageData = Awaited<ReturnType<typeof loadRosterProgression>>;
export type RecruitingSummaryPageData = Awaited<ReturnType<typeof loadRecruitingSummary>>;
export type RecruitingPageData = Awaited<ReturnType<typeof loadRecruiting>>;
export type RosterCutsPageData = Awaited<ReturnType<typeof loadRosterCuts>>;
export type RatingsStatsPageData = Awaited<ReturnType<typeof loadRatingsStats>>;
export type TeamRankingsPageData = Awaited<ReturnType<typeof loadTeamRankings>>;
export type TeamStatsPageData = Awaited<ReturnType<typeof loadTeamStats>>;
export type StandingsPageData = Awaited<ReturnType<typeof loadStandings>>;
export type TeamRosterPageData = Awaited<ReturnType<typeof loadTeamRoster>>;
export type TeamHistoryPageData = Awaited<ReturnType<typeof loadTeamHistory>>;
export type RankingsPageData = Awaited<ReturnType<typeof loadRankings>>;
export type PlayerPageData = Awaited<ReturnType<typeof loadPlayer>>;
export type TeamInfoData = Awaited<ReturnType<typeof getTeamInfo>>;
export type AvailableNonConOpponentsData = Awaited<ReturnType<typeof listAvailableOpponents>>;
export type PlayerLeadersPageData = Awaited<ReturnType<typeof loadPlayerLeaders>>;
export type PlayoffBracketPageData = Awaited<ReturnType<typeof loadPlayoffBracket>>;
export type PlayoffPicturePageData = Awaited<ReturnType<typeof loadPlayoffPicture>>;
export type ResumeComparisonPageData = Awaited<ReturnType<typeof loadResumeComparison>>;
export type BowlGamesPageData = Awaited<ReturnType<typeof loadBowlGames>>;
export type AdvancedStatsPageData = Awaited<ReturnType<typeof loadAdvancedStats>>;
export type PostseasonProjectionsPageData = Awaited<ReturnType<typeof loadPostseasonProjections>>;
